sudo: false
dist: trusty
language: ruby
cache: builder
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - rake test
rvm: 1.11.3.9
bundler_args: --without acceptance
notifications:
  email: false
