---
plugins:
  vagrant-vbguest: 0.14.2
  vagrant-hostmanager: 1.8.6
  vagrant-share: 1.1.5
  vagrant-librarian-puppet: 0.9.2
  vagrant-puppet-install: 4.0.1
  vagrant-persistent-storage: 0.0.26
vbguest: 
  enable: false
hostmanager:
  enable: true
  manage_host: true
  manage_guest: true
puppet:
  enable: true
  version: '4.8.1'
  puppet_dir: 'puppet'
persistent-storage:
  enable: false
box: bento/centos-7.3
roles:
  standalone:
    environment: 'hue'
    cpu: 1
    memory: 1024
    count: 1
    data:
      enable: false
