---
plugins:
  vagrant-vbguest: 0.13.0
  vagrant-hostmanager: 1.8.5
  vagrant-share: 1.1.5
  vagrant-librarian-puppet: 0.9.2
  vagrant-puppet-install: 4.0.1
  vagrant-persistent-storage: 0.0.23 # 0.0.24
vbguest: 
  enable: false
hostmanager:
  enable: true
  manage_host: true
  manage_guest: true
puppet:
  enable: true
  version: '4.8.1'
  puppet_dir: 'puppet'
persistent-storage:
  enable: false
box: bento/centos-7.2
roles:
  journalnode:
    environment: 'hadoop'
    cpu: 1
    memory: 1024
    count: 3
    data:
      enable: false
  namenode:
    environment: 'hadoop'
    cpu: 1
    memory: 1024
    count: 2
    data:
      enable: false
  datanode:
    environment: 'hadoop'
    cpu: 1
    memory: 1024
    count: 1
    data:
      enable: false
  hive:
    environment: 'hadoop'
    cpu: 1
    memory: 1024
    count: 1
    data:
      enable: false
