---
plugins:
  vagrant-vbguest: 0.14.2
  vagrant-hostmanager: 1.8.7
  vagrant-librarian-puppet: 0.9.2
  vagrant-puppet-install: 4.1.0
  vagrant-persistent-storage: 0.0.34
vbguest: 
  enable: false
hostmanager:
  enable: true
  manage_host: true
  manage_guest: true
puppet:
  enable: true
  version: '4.10.1'
  puppet_dir: 'puppet'
persistent-storage:
  enable: false
roles:
  windows:
    os: 'win2012r2'
    environment: 'default'
    cpu: 1
    memory: 2048
    count: 1
    data:
      enable: false
  ubuntu:
    os: 'ubuntu16'
    environment: 'default'
    cpu: 1
    memory: 1024
    count: 1
    data:
      enable: false
  centos:
    os: 'centos73'
    environment: 'default'
    cpu: 1
    memory: 1024
    count: 1
    data:
      enable: false

