---
plugins:
  vagrant-vbguest: 0.14.2
  vagrant-hostmanager: 1.8.7
  vagrant-librarian-puppet: 0.9.2
  vagrant-puppet-install: 4.1.0
  vagrant-persistent-storage: 0.0.34
vbguest: 
  enable: false
hostmanager:
  enable: true
  manage_host: true
  manage_guest: true
puppet:
  enable: true
  version: '4.10.1'
  puppet_dir: 'puppet'
persistent-storage:
  enable: false
boxes:
  centos73: 'bento/centos-7.3'
  ubuntu16: 'ubuntu/xenial64'
  win2012r2: 'opentable/win-2012r2-standard-amd64-nocm'

