---
roles:
  standalone1:
    os: 'centos73'
    environment: 'sensu'
    cpu: 2
    memory: 2048
    count: 1
  standalone2:
    os: 'centos73'
    environment: 'grafana'
    cpu: 2
    memory: 2048
    count: 1
  standalone3:
    os: 'centos73'
    environment: 'kafka'
    cpu: 2
    memory: 2048
    count: 1
